#==================
#   MoneyThief
#==================

#==================
#     General
#==================

# Check for updates
update-check: true

# Log kills
enable-logging: true

# Notify server if a mob is missing in config
notify-missing-mob: true

#==================
#     Metrics
#==================

#Allows the plugin to send anonymous usage statistics to mcstats.org
metrics: true

#==================
#       PVP
#==================

pvp:
  # Percent of money that a player loses when killed via PVP
  percent-taken: 10
  # Percent of money victim loses that doesn't go to killer
  percent-lost: 10

#==================
#       PVE
#==================
pve:
  # Percent of money that a player loses when killed via PVE
  percent-lost: 5
  # Artificially spawned mobs yeild rewards
  artificial-spawn: true

#==================
#    Messages
#==================
  # All messages can be processed with the following codes:
  #   \n - New line
  #   &X - Colour code
  #
  # == How Majors and Minors work ==
  #   The major is the whole integer, unrounded. The minor is the decimal of a value multiplied by 100.
  #   You can use them to represent for example gold and silver coins.
  #   ex) If a player gains $12.34, the major would be 12 and the minor would be 53. Thus:
  #      "Player gained 12 gold coins and 34 silver coins."

message:
  general:
    no-perms: "&4Bugger off, you don't have the right permissions!"



  pvp:
      # PVP messages can be processed with the following codes:
      #   %VICTIM - Player who was killed
      #   %KILLER - Player who killed %VICTIM
      #   %MONEYTAKEN - Total money take from %VICTIM
      #     %MAJORTAKEN - Major of %MONEYTAKEN
      #     %MINORTAKEN - Minor of %MONEYTAKEN
      #   %MONEYLOST - Money lost from %MONEYTAKEN
      #     %MAJORLOST - Major of %MONEYLOST
      #     %MINORLOST - Minor of %MONEYLOST
      #   %MONEYGAINED - Money given to %KILLER
      #     %MAJORGAINED - Major of %MONEYGAINED
      #     %MINORGAINED - Minor of %MONEYGAINED

    # Sent to the victim/killer respectively upon a pvp event
    victim: "&6You were killed by %KILLER&6.\n&6You lost $%MONEYTAKEN, and $%MONEYLOST of it disappeared into the aether."
    killer: "&6You killed %VICTIM&6, and looted $%MONEYGAINED off of the body."

    # Sent to the victim/killer respectively upon a pvp event when victim has no money
    victim-zero: "&6You were killed by %KILLER&6, but you had nothing to lose!"
    killer-zero: "&6You killed %VICTIM&6, but they had no money to loot."

    # Replaces pvp death messages. Set to "none" to not change message, set to "disable" to disable it entirely.
    death-message: "none"

  pve:
      # PVE messages can be processed with the following codes:
      #   %MOBNAME - Name of the mob in question
      #   %A - 'a' or 'an', depending on %MOBNAME
      #   %MONEY - Money gained/lost (depending on situation)
      #     %MAJOR - Major of %MONEY
      #     %MINOR - Minor of %MONEY
      #   %CAUSE - Cause of death when not a mob

    # Sent to player when they kill a mob
    killer: "&6You gained $%MONEY for killing %A %MOBNAME."

    # Sent to the player when killed by a mob
    victim-mob: "&6You were killed by %A %MOBNAME, and $%MONEY disappeared into the aether."
    victim-mob-zero: "&6You were killed by %A %MOBNAME, but you had nothing to lose!"

    # Sent to player when killed by not a mob
    victim-env: "&6You died from %CAUSE, and $%MONEY disappeared into the aether."
    victim-env-zero: "&6You died from %CAUSE, but had nothing to lose!"

    # Used as %CAUSE when death cause is unknown
    generic-cause: "something"

    # Replaces PVE death messages. Set to "none" to not change message, set to "disable" to disable it entirely.
    death-message: "none"

#==================
#       Mobs
#==================
  # Mobs are expandable. If I've missed one, simply put it's name below.
  # Mobs have two values, a high and a low. The value given to the killer
  # randomly calculated between the two values.
mobs:
  PIG:
  - 5.0
  - 10.0
  COW:
  - 5.0
  - 10.0
  SHEEP:
  - 5.0
  - 10.0
  CHICKEN:
  - 5.0
  - 10.0
  BAT:
  - 5.0
  - 10.0
  RABBIT:
  - 5.0
  - 10.0
  SNOWMAN:
  - 5.0
  - 10.0
  IRON_GOLEM:
  - 5.0
  - 10.0
  MUSHROOM_COW:
  - 5.0
  - 10.0
  OCELOT:
  - 5.0
  - 10.0
  SQUID:
  - 5.0
  - 10.0
  VILLAGER:
  - 5.0
  - 10.0
  WOLF:
  - 5.0
  - 10.0
  HORSE:
  - 5.0
  - 10.0
  CAVE_SPIDER:
  - 10.0
  - 20.0
  SLIME:
  - 5.0
  - 10.0
  CREEPER:
  - 10.0
  - 20.0
  SKELETON:
  - 10.0
  - 20.0
  ZOMBIE:
  - 10.0
  - 20.0
  ENDER_DRAGON:
  - 150.0
  - 200.0
  ENDERMAN:
  - 10.0
  - 20.0
  ENDERMITE:
  - 5.0
  - 10.0
  GHAST:
  - 10.0
  - 20.0
  GUARDIAN:
  - 10.0
  - 20.0
  MAGMA_CUBE:
  - 10.0
  - 20.0
  PIG_ZOMBIE:
  - 10.0
  - 20.0
  SILVERFISH:
  - 10.0
  - 20.0
  SPIDER:
  - 10.0
  - 20.0
  WITCH:
  - 10.0
  - 20.0
  WITHER:
  - 150.0
  - 200.0
  # DEFAULT will apply to any mob that's not listed here.
  #DEFAULT:
  #- 5.0
  #- 10.0