#==================
#   MoneyThief
#==================

#==================
#     General
#==================

# Check for updates
update-check: true

# Log kills
enable-logging: true

# Notify server if a mob is missing in config
notify-missing-mob: true

#==================
#     Metrics
#==================

#Allows the plugin to send anonymous usage statistics to mcstats.org
metrics: false

#==================
#       PVP
#==================

pvp:
  # Percent of money that a player loses when killed via PVP
  percent-taken: 10
  # Percent of money victim loses that doesn't go to killer
  percent-lost: 0

#==================
#       PVE
#==================
pve:
  # Percent of money that a player loses when killed via PVE
  percent-lost: 5
  # Artificially spawned mobs yeild rewards
  artificial-spawn: true

#==================
#    Messages
#==================
  # All messages can be processed with the following codes:
  #   \n - New line
  #   &X - Colour code
  #
  # == How Majors and Minors work ==
  #   The major is the whole integer, unrounded. The minor is the decimal of a value multiplied by 100.
  #   You can use them to represent for example gold and silver coins.
  #   ex) If a player gains $12.34, the major would be 12 and the minor would be 53. Thus:
  #      "Player gained 12 gold coins and 34 silver coins."

message:
  general:
    no-perms: "&4Go away, you don't have the right permissions!"

  pvp:
      # PVP messages can be processed with the following codes:
      #   %VICTIM - Player who was killed
      #   %KILLER - Player who killed %VICTIM
      #   %MONEYTAKEN - Total money take from %VICTIM
      #     %MAJORTAKEN - Major of %MONEYTAKEN
      #     %MINORTAKEN - Minor of %MONEYTAKEN
      #   %MONEYLOST - Money lost from %MONEYTAKEN
      #     %MAJORLOST - Major of %MONEYLOST
      #     %MINORLOST - Minor of %MONEYLOST
      #   %MONEYGAINED - Money given to %KILLER
      #     %MAJORGAINED - Major of %MONEYGAINED
      #     %MINORGAINED - Minor of %MONEYGAINED

    # Sent to the victim/killer respectively upon a pvp event
    victim: "&6You were killed by %KILLER&6.\n&6You lost $%MONEYTAKEN, and $%MONEYLOST of it disappeared into the aether."
    killer: "&6You killed %VICTIM&6, and looted $%MONEYGAINED off of the body."

    # Sent to the victim/killer respectively upon a pvp event when victim has no money
    victim-zero: "&6You were killed by %KILLER&6, but you had nothing to lose!"
    killer-zero: "&6You killed %VICTIM&6, but they had no money to loot."

    # Replaces pvp death messages. Set to "none" to not change message, set to "disable" to disable it entirely.
    death-message: "none"

  pve:
      # PVE messages can be processed with the following codes:
      #   %MOBNAME - Name of the mob in question
      #   %A - 'a' or 'an', depending on %MOBNAME
      #   %MONEY - Money gained/lost (depending on situation)
      #     %MAJOR - Major of %MONEY
      #     %MINOR - Minor of %MONEY
      #   %CAUSE - Cause of death when not a mob

    # Sent to player when they kill a mob
    killer: "&6You gained $%MONEY for killing %A %MOBNAME."

    # Sent to the player when killed by a mob
    victim-mob: "&6You were killed by %A %MOBNAME, and $%MONEY disappeared into the aether."
    victim-mob-zero: "&6You were killed by %A %MOBNAME, but you had nothing to lose!"

    # Sent to player when killed by not a mob
    victim-env: "&6You died from %CAUSE, and $%MONEY disappeared into the aether."
    victim-env-zero: "&6You died from %CAUSE, but had nothing to lose!"

    # Used as %CAUSE when death cause is unknown
    generic-cause: "something"

    # Replaces PVE death messages. Set to "none" to not change message, set to "disable" to disable it entirely.
    death-message: "none"

#==================
#      Groups
#==================
groups:
  # Groups are expandable. First, name the group. Second, you need two arguments.
  # - The first argument is the bonus they receive for killing a mob.
  # - The second argument is the reduction they get for dying to a pve event.
  # Here's an example:
  #vip:
  #- 2.0
  #- 0.5
  # In this example, anyone in the group 'vip' will receive twice as much
  # for killing a mob, and half as much for dying to pve event.
  #
  # To use what's created here, give the player in question the permission node "moneythief.group.<name>".
  # Thus, to use vip you would give the group in your permissions plugin "moneythief.group.vip".
  #   - This is so that it's compatible with any permission plugin you wish to use.


#==================
#       Mobs
#==================
  # Mobs are expandable. If I've missed one, simply put it's name below.
  # Mobs have two values, a high and a low. The value given to the killer
  # randomly calculated between the two values.
#Passive and Neutral Mobs
mobs:
  AXOLOTL:
  - 4.0
  - 6.0
  BAT:
  - 1.0
  - 2.0
  BEE:
  - 0.1
  - 0.2
  CAT:
  - 1.0
  - 2.0
  CHICKEN:
  - 0.0
  - 1.0
  COD:
  - 0.0
  - 0.5
  COW:
  - 1.0
  - 2.0
  DOLPHIN:
  - 2.0
  - 3.0
  DONKEY:
  - 3.0
  - 4.0
  ENDERMAN:
  - 5.0
  - 15.0
  FOX:
  - 2.0
  - 5.0
  GLOW_SQUID:
  - 2.0
  - 3.0
  GOAT:
  - 2.0
  - 3.0
  HORSE:
  - 1.0
  - 2.0
  IRON_GOLEM:
  - 0.0
  - 0.0
  LLAMA:
  - 1.0
  - 4.0
  MUSHROOM_COW:
  - 1.0
  - 3.0
  MULE:
  - 3.0
  - 4.0
  OCELOT:
  - 1.0
  - 3.0
  PANDA:
  - 3.0
  - 4.0
  PARROT:
  - 1.0
  - 2.0
  PIG:
  - 1.0
  - 2.0
  PIGLIN:
  - 2.0
  - 3.0
  POLAR_BEAR:
  - 8.0
  - 10.0
  PUFFERFISH:
  - 1.0
  - 2.0
  RABBIT:
  - 1.0
  - 1.0
  SALMON:
  - 0.0
  - 0.5
  SHEEP:
  - 1.0
  - 2.0
  SNOWMAN:
  - 1.0
  - 10.0
  SQUID:
  - 0.0
  - 0.5
  STRIDER:
  - 2.0
  - 4.0
  TROPICAL_FISH:
  - 0.5
  - 0.75
  TURTLE:
  - 1.0
  - 1.5
  VILLAGER:
  - 0.0
  - 0.0
  WANDERING_TRADER:
  - 0.0
  - 0.0
  WOLF:
  - 1.0
  - 3.0
#Hostile Mobs
  BLAZE:
  - 10.0
  - 15.0
  CAVE_SPIDER:
  - 3.0
  - 5.0
  CREEPER:
  - 1.0
  - 3.0
  DROWNED:
  - 3.0
  - 5.0
  ELDER_GUARDIAN:
  - 20.0
  - 40.0
  ENDER_DRAGON:
  - 150.0
  - 200.0
  ENDERMITE:
  - 5.0
  - 8.0
  EVOKER:
  - 10.0
  - 30.0
  GHAST:
  - 5.0
  - 15.0  
  GUARDIAN:
  - 2.0
  - 8.0
  HOGLIN:
  - 8.0
  - 15.0
  HUSK:
  - 3.0
  - 4.0
  MAGMA_CUBE:
  - 5.0
  - 10.0
  PHANTOM:
  - 20.0
  - 40.0
  PIGLIN_BRUTE:
  - 20.0
  - 30.0
  ZOMBIFIED_PIGLIN:
  - 10.0
  - 15.0
  PILLAGER:
  - 10.0
  - 15.0
  RAVAGER:
  - 40.0
  - 50.0
  SHULKER:
  - 15.0
  - 20.0
  SILVERFISH:
  - 1.0
  - 2.0
  SKELETON:
  - 2.0
  - 4.0
  SLIME:
  - 2.0
  - 3.0
  SPIDER:
  - 1.0
  - 2.0
  STRAY:
  - 3.0
  - 5.0
  VEX:
  - 10.0
  - 15.0
  VINDICATOR:
  - 20.0
  - 25.0
  WITCH:
  - 3.0
  - 5.0
  WITHER:
  - 100.0
  - 150.0
  WITHER_SKELETON:
  - 30.0
  - 50.0
  ZOGLIN:
  - 5.0
  - 8.0
  ZOMBIE:
  - 2.0
  - 3.0
  ZOMBIE_VILLAGER:
  - 10.0
  - 20.0
  # When enabled, DEFAULT will apply to any mob that's not listed here.
  #DEFAULT:
  #- 5.0
  #- 10.0
