name: MoneyThief
main: io.github.ratismal.moneythief.MoneyThief
author: Ratismal
version: 1.3.1
api-version: 1.18
depend: [Vault]
commands:
  moneythief:
      description: Base MoneyThief command.
      usage: Do /moneythief for a list of commands
      permission: moneythief
      permission-message: Bugger off, you don't have the rights to do that!